### ISSUE TITLE
Promise is not defined

### ISSUE THREAD

**Issue by snowy13** [eris-ltd/eris-eggbank#3]
Error while running terminal command.
To reproduce:
`sudo node eggbank.js terminal [contract_manager_account_name]`
At prompt, enter command eg. `register`
Error message:
```
/home/pi/eris-eggbank/eggbank.js:235
    return new Promise(function (resolve, reject) {
               ^
ReferenceError: Promise is not defined
    at EbbTerminal.ebbRegister (/home/pi/eris-eggbank/eggbank.js:235:16)
    at Object._parse [as parse] (/home/pi/eris-eggbank/node_modules/lineparser-promised/lineparser-promised.js:335:24)
    at EbbTerminal.terminal (/home/pi/eris-eggbank/eggbank.js:436:21)
    at EbbTerminal.start (/home/pi/eris-eggbank/eggbank.js:446:10)
    at eggbank (/home/pi/eris-eggbank/eggbank.js:467:12)
    at Object.<anonymous> (/home/pi/eris-eggbank/eggbank.js:477:1)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
```

Tested with node v12.10

Fixed by:
`npm install es6-promise`
Then adding this line to top of eggbank.js:
`var Promise = require('es6-promise').Promise;`

Please note that I am a total newb to node!
Does this fix the problem or do I need non legacy node with io.js?

**Comment by snowy13** [comment]
Tested and reproduced error with node v4.1.1.
Fix above removes the error.

**Comment by zramsay** [comment]
hi @snowy13 thanks for the bug report (and solution)! To clarify you last comment, does the fix:
`npm install es6-promise` 
then adding the new line 
`var Promise = require('es6-promise').Promise;` 
work on `node v4.1.1`? 
If so, we're happy to accept a pull request for this fix!

Otherwise, I'll have let @shuangjj chime in

**Comment by snowy13** [comment]
hi @zramsay  confirm testing on `node v4.1.1`
Issuing pull request.

**Comment by shuangjj** [comment]
@snowy13 I'm using `node v4.4.7` on my RPi, which has native `Promise` support. If your version of `node` doesn't have `Promise`, you need to install and include `es6-promise` instead. @zramsay

**Comment by snowy13** [comment]
Awesome thanks @shuangjj !
Learning to navigate the node ecosystem...

**Comment by zramsay** [comment]
Closing as resolved by using a more recent `node version`. Note that this repo is now deprecated in favour of a harmonized hello-world/examples repo: https://github.com/eris-ltd/hello-eris ... see the [PR here](https://github.com/eris-ltd/hello-eris/pull/4)
